#워크 플로우 이름 지정
name: main_workflows

#워크 플로우 이벤트 트리거
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, develop]

#JOB
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "test"